"""create_family_wallet_tables

Revision ID: 5f9043849e48
Revises: 0006
Create Date: 2026-07-07 01:45:41.339352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f9043849e48'
down_revision: Union[str, None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('invite_code', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_wallets_invite_code'), 'family_wallets', ['invite_code'], unique=True)
    op.create_index(op.f('ix_family_wallets_owner_id'), 'family_wallets', ['owner_id'], unique=False)
    op.create_table('family_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_wallet_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_wallet_id'], ['family_wallets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_members_family_wallet_id'), 'family_members', ['family_wallet_id'], unique=False)
    op.create_index(op.f('ix_family_members_user_id'), 'family_members', ['user_id'], unique=False)
    op.create_table('shared_expenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_wallet_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('paid_by_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['family_wallet_id'], ['family_wallets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paid_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_expenses_family_wallet_id'), 'shared_expenses', ['family_wallet_id'], unique=False)
    op.create_index(op.f('ix_shared_expenses_paid_by_id'), 'shared_expenses', ['paid_by_id'], unique=False)
    op.drop_index('idx_budgets_category_id', table_name='budgets')
    op.drop_constraint('budgets_category_id_fkey', 'budgets', type_='foreignkey')
    op.create_foreign_key(None, 'budgets', 'categories', ['category_id'], ['id'])
    op.drop_column('budgets', 'updated_at')
    op.alter_column('categories', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('categories', 'slug',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('categories', 'display_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('categories', 'icon',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('categories', 'color',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index('ux_categories_system_name', table_name='categories', postgresql_where='(system = true)')
    op.drop_index('ux_categories_user_name', table_name='categories', postgresql_where='(system = false)')
    op.create_index(op.f('ix_categories_parent_category_id'), 'categories', ['parent_category_id'], unique=False)
    op.alter_column('learning_events', 'feedback_source',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('learning_events', 'processed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('merchant_aliases', 'alias',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('merchant_rules', 'confidence_weight',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('80'))
    op.alter_column('merchants', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('merchants', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index('idx_transactions_dashboard_optimized', table_name='transactions', postgresql_include=['amount', 'merchant', 'category_id'])
    op.create_index('idx_tx_user_date_cat', 'transactions', ['user_id', 'transaction_date', 'category_id', 'amount'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_date'), 'transactions', ['transaction_date'], unique=False)
    op.alter_column('user_overrides', 'correction_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('user_overrides', 'last_corrected',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_overrides', 'last_corrected',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_overrides', 'correction_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('ix_transactions_transaction_date'), table_name='transactions')
    op.drop_index('idx_tx_user_date_cat', table_name='transactions')
    op.create_index('idx_transactions_dashboard_optimized', 'transactions', ['user_id', sa.text('transaction_date DESC')], unique=False, postgresql_include=['amount', 'merchant', 'category_id'])
    op.alter_column('merchants', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('merchants', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('merchant_rules', 'confidence_weight',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('80'))
    op.alter_column('merchant_aliases', 'alias',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('learning_events', 'processed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('learning_events', 'feedback_source',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_categories_parent_category_id'), table_name='categories')
    op.create_index('ux_categories_user_name', 'categories', ['user_id', sa.text('lower(name)')], unique=True, postgresql_where='(system = false)')
    op.create_index('ux_categories_system_name', 'categories', [sa.text('lower(name)')], unique=True, postgresql_where='(system = true)')
    op.alter_column('categories', 'color',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('categories', 'icon',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('categories', 'display_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('categories', 'slug',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('categories', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('budgets', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'budgets', type_='foreignkey')
    op.create_foreign_key('budgets_category_id_fkey', 'budgets', 'categories', ['category_id'], ['id'], ondelete='RESTRICT')
    op.create_index('idx_budgets_category_id', 'budgets', ['category_id'], unique=False)
    op.drop_index(op.f('ix_shared_expenses_paid_by_id'), table_name='shared_expenses')
    op.drop_index(op.f('ix_shared_expenses_family_wallet_id'), table_name='shared_expenses')
    op.drop_table('shared_expenses')
    op.drop_index(op.f('ix_family_members_user_id'), table_name='family_members')
    op.drop_index(op.f('ix_family_members_family_wallet_id'), table_name='family_members')
    op.drop_table('family_members')
    op.drop_index(op.f('ix_family_wallets_owner_id'), table_name='family_wallets')
    op.drop_index(op.f('ix_family_wallets_invite_code'), table_name='family_wallets')
    op.drop_table('family_wallets')
    # ### end Alembic commands ###
